name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:  # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2
      - name: Gerar animação
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: dist/github-contribution-grid-snake.svg
      - name: Atualizar snake no repositório
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
